language: python
cache: pip
before_script:
  - pip install tox coveralls
script:  tox
after_success:
  - coveralls || echo "intermittent coveralls failure"
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
