language: python
cache: pip
env:
  - AWS_DEFAULT_REGION=us-east-1
before_script:
  - pip install tox
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
